set shell := ["bash", "-euo", "pipefail", "-c"]

k3s:
    curl -sfL https://get.k3s.io | sh - \
      #INSTALL_K3S_EXEC="server --flannel-backend=none --disable-kube-proxy --disable servicelb --disable-network-policy --disable traefik" sh -
    mkdir -p ~/.kube
    sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    sudo chown "$USER:$USER" ~/.kube/config

cert-manager:
    KUBECONFIG=~/.kube/config helmfile -f helmfile.d/00-cert-manager-crds.yaml apply
secret:
    kubectl create namespace external-secrets
    kubectl create secret generic sops-age --from-file=$HOME/age.agekey -n external-secrets
flux:
    KUBECONFIG=~/.kube/config flux bootstrap github \
      --token-auth \
      --owner=heroaero-dev \
      --repository=kube-homelab-v2 \
      --branch=main \
      --path=kubernetes/flux/cluster \
      --personal

